name: second_process
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  image_cropper: ^5.0.0
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  webview_flutter: ^4.4.1
  flutter_webview_plugin: ^0.4.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  firebase_messaging: ^14.7.5
  rxdart: ^0.27.7
  google_sign_in: ^6.1.6


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/chevronleft.png
    - assets/bookmark.png
    - assets/profile.jpg
    - assets/myname.jpg
    - assets/goblin.jpg
    - assets/mgig.jpg
    - assets/it.jpg
    - assets/dots.jpg
    - assets/saw.jpg
    - assets/after.jpg
    - assets/maghrib.jpg
    - assets/call.jpeg
    - assets/default.jpg
