// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2H6_Y4jFwK7O0ucuGMLwYvdpvs_OgT7M',
    appId: '1:387544421660:web:f775f0221d8314030e56d9',
    messagingSenderId: '387544421660',
    projectId: 'try-firebase1-3a4ab',
    authDomain: 'try-firebase1-3a4ab.firebaseapp.com',
    storageBucket: 'try-firebase1-3a4ab.appspot.com',
    measurementId: 'G-2WGYFMGLJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCok0fXuyamqsH11HoAAf0eCEkQKed3X-g',
    appId: '1:387544421660:android:d3c2216eba5da4f50e56d9',
    messagingSenderId: '387544421660',
    projectId: 'try-firebase1-3a4ab',
    storageBucket: 'try-firebase1-3a4ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuZlIu8bizXFKCKu2v8hXr3NG0EpsjaI',
    appId: '1:387544421660:ios:7078b80d65c074a50e56d9',
    messagingSenderId: '387544421660',
    projectId: 'try-firebase1-3a4ab',
    storageBucket: 'try-firebase1-3a4ab.appspot.com',
    iosBundleId: 'com.example.secondProcess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuZlIu8bizXFKCKu2v8hXr3NG0EpsjaI',
    appId: '1:387544421660:ios:fb530a2e19c44d750e56d9',
    messagingSenderId: '387544421660',
    projectId: 'try-firebase1-3a4ab',
    storageBucket: 'try-firebase1-3a4ab.appspot.com',
    iosBundleId: 'com.example.secondProcess.RunnerTests',
  );
}
